packages:
- 'lezer-playground'
- 'packages/all-folds-zig'
- 'packages/codemirror-awesome-line-wrapping'
- 'packages/codemirror-editor-in-chief'
- 'packages/codemirror-subtle-color-picker'
- 'packages/codemirror-x-react'
- 'packages/composite-key'
- 'packages/dral-codemirror-helpers'
- 'packages/dral-lezer-helpers'
- 'packages/find-positions-zig'
- 'packages/lezer-generator-worker'
- 'packages/lezer-inspector'
- 'packages/lezer-lezer-error'
- 'packages/modern-map'
- 'packages/react-codemirror-widget'
- 'packages/transform-javascript'
- 'packages/worker-typescript-magic'
